/*
 * WireMock
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.26.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Body10
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-02T03:16:43.324Z[GMT]")
public class Body10 {
  @SerializedName("filters")
  private Object filters = null;

  @SerializedName("targetBaseUrl")
  private String targetBaseUrl = null;

  public Body10 filters(Object filters) {
    this.filters = filters;
    return this;
  }

   /**
   * Get filters
   * @return filters
  **/
  @Schema(description = "")
  public Object getFilters() {
    return filters;
  }

  public void setFilters(Object filters) {
    this.filters = filters;
  }

  public Body10 targetBaseUrl(String targetBaseUrl) {
    this.targetBaseUrl = targetBaseUrl;
    return this;
  }

   /**
   * Target URL when using the record and playback API
   * @return targetBaseUrl
  **/
  @Schema(example = "http://example.mocklab.io", description = "Target URL when using the record and playback API")
  public String getTargetBaseUrl() {
    return targetBaseUrl;
  }

  public void setTargetBaseUrl(String targetBaseUrl) {
    this.targetBaseUrl = targetBaseUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body10 body10 = (Body10) o;
    return Objects.equals(this.filters, body10.filters) &&
        Objects.equals(this.targetBaseUrl, body10.targetBaseUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(filters, targetBaseUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body10 {\n");
    
    sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
    sb.append("    targetBaseUrl: ").append(toIndentedString(targetBaseUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
