/*
 * WireMock
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.26.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.InlineResponse2004Scenarios;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse2004
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-02T03:16:43.324Z[GMT]")
public class InlineResponse2004 {
  @SerializedName("scenarios")
  private List<InlineResponse2004Scenarios> scenarios = null;

  public InlineResponse2004 scenarios(List<InlineResponse2004Scenarios> scenarios) {
    this.scenarios = scenarios;
    return this;
  }

  public InlineResponse2004 addScenariosItem(InlineResponse2004Scenarios scenariosItem) {
    if (this.scenarios == null) {
      this.scenarios = new ArrayList<InlineResponse2004Scenarios>();
    }
    this.scenarios.add(scenariosItem);
    return this;
  }

   /**
   * Get scenarios
   * @return scenarios
  **/
  @Schema(description = "")
  public List<InlineResponse2004Scenarios> getScenarios() {
    return scenarios;
  }

  public void setScenarios(List<InlineResponse2004Scenarios> scenarios) {
    this.scenarios = scenarios;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2004 inlineResponse2004 = (InlineResponse2004) o;
    return Objects.equals(this.scenarios, inlineResponse2004.scenarios);
  }

  @Override
  public int hashCode() {
    return Objects.hash(scenarios);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2004 {\n");
    
    sb.append("    scenarios: ").append(toIndentedString(scenarios)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
