/*
 * WireMock
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.26.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Body8;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse2002
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-02T03:16:43.324Z[GMT]")
public class InlineResponse2002 {
  @SerializedName("nearMisses")
  private List<Body8> nearMisses = null;

  public InlineResponse2002 nearMisses(List<Body8> nearMisses) {
    this.nearMisses = nearMisses;
    return this;
  }

  public InlineResponse2002 addNearMissesItem(Body8 nearMissesItem) {
    if (this.nearMisses == null) {
      this.nearMisses = new ArrayList<Body8>();
    }
    this.nearMisses.add(nearMissesItem);
    return this;
  }

   /**
   * Get nearMisses
   * @return nearMisses
  **/
  @Schema(description = "")
  public List<Body8> getNearMisses() {
    return nearMisses;
  }

  public void setNearMisses(List<Body8> nearMisses) {
    this.nearMisses = nearMisses;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2002 inlineResponse2002 = (InlineResponse2002) o;
    return Objects.equals(this.nearMisses, inlineResponse2002.nearMisses);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nearMisses);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2002 {\n");
    
    sb.append("    nearMisses: ").append(toIndentedString(nearMisses)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
