/*
 * WireMock
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.26.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiCallback;
import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.Configuration;
import io.swagger.client.Pair;
import io.swagger.client.ProgressRequestBody;
import io.swagger.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import in.ravikalla.wiremockbackup.service.WiremockOperationsService;

import java.io.IOException;


import io.swagger.client.model.Body;
import io.swagger.client.model.Body1;
import io.swagger.client.model.Body2;
import io.swagger.client.model.Body3;
import io.swagger.client.model.InlineResponse200;
import io.swagger.client.model.InlineResponse201;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class StubMappingsApi {
	private static final Logger L = LogManager.getLogger(StubMappingsApi.class);

    private ApiClient apiClient;

    public StubMappingsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public StubMappingsApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for adminMappingsDelete
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call adminMappingsDeleteCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsDeleteCall(...)");
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/__admin/mappings";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        L.debug("End : StubMappingsApi.adminMappingsDeleteCall(...)");
        return apiClient.buildCall(localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call adminMappingsDeleteValidateBeforeCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsDeleteValidateBeforeCall(...)");
        com.squareup.okhttp.Call call = adminMappingsDeleteCall(progressListener, progressRequestListener);
        L.debug("End : StubMappingsApi.adminMappingsDeleteValidateBeforeCall(...)");
        return call;

        
        
        
        
    }

    /**
     * Delete all stub mappings
     * 
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void adminMappingsDelete() throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsDelete()");
        adminMappingsDeleteWithHttpInfo();
        L.debug("Start : StubMappingsApi.adminMappingsDelete()");
    }

    /**
     * Delete all stub mappings
     * 
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> adminMappingsDeleteWithHttpInfo() throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsDeleteWithHttpInfo()");
        com.squareup.okhttp.Call call = adminMappingsDeleteValidateBeforeCall(null, null);
        L.debug("Start : StubMappingsApi.adminMappingsDeleteWithHttpInfo()");
        return apiClient.execute(call);
    }

    /**
     * Delete all stub mappings (asynchronously)
     * 
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call adminMappingsDeleteAsync(final ApiCallback<Void> callback) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsDeleteAsync()");
        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = adminMappingsDeleteValidateBeforeCall(progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        L.debug("End : StubMappingsApi.adminMappingsDeleteAsync()");
        return call;
    }
    /**
     * Build call for adminMappingsFindByMetadataPost
     * @param body  (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call adminMappingsFindByMetadataPostCall(Body2 body, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsFindByMetadataPostCall()");
        Object localVarPostBody = body;
        
        // create path and map variables
        String localVarPath = "/__admin/mappings/find-by-metadata";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        L.debug("End : StubMappingsApi.adminMappingsFindByMetadataPostCall()");
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call adminMappingsFindByMetadataPostValidateBeforeCall(Body2 body, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsFindByMetadataPostValidateBeforeCall(...)");
        // verify the required parameter 'body' is set
        if (body == null) {
            throw new ApiException("Missing the required parameter 'body' when calling adminMappingsFindByMetadataPost(Async)");
        }
        
        com.squareup.okhttp.Call call = adminMappingsFindByMetadataPostCall(body, progressListener, progressRequestListener);
        L.debug("End : StubMappingsApi.adminMappingsFindByMetadataPostValidateBeforeCall(...)");
        return call;

        
        
        
        
    }

    /**
     * 
     * Find stubs by matching on their metadata
     * @param body  (required)
     * @return InlineResponse200
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public InlineResponse200 adminMappingsFindByMetadataPost(Body2 body) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsFindByMetadataPost(...)");
        ApiResponse<InlineResponse200> resp = adminMappingsFindByMetadataPostWithHttpInfo(body);
        L.debug("End : StubMappingsApi.adminMappingsFindByMetadataPost(...)");
        return resp.getData();
    }

    /**
     * 
     * Find stubs by matching on their metadata
     * @param body  (required)
     * @return ApiResponse&lt;InlineResponse200&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<InlineResponse200> adminMappingsFindByMetadataPostWithHttpInfo(Body2 body) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsFindByMetadataPostWithHttpInfo(...)");
        com.squareup.okhttp.Call call = adminMappingsFindByMetadataPostValidateBeforeCall(body, null, null);
        Type localVarReturnType = new TypeToken<InlineResponse200>(){}.getType();
        L.debug("End : StubMappingsApi.adminMappingsFindByMetadataPostWithHttpInfo(...)");
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Find stubs by matching on their metadata
     * @param body  (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call adminMappingsFindByMetadataPostAsync(Body2 body, final ApiCallback<InlineResponse200> callback) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsFindByMetadataPostAsync(...)");
        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = adminMappingsFindByMetadataPostValidateBeforeCall(body, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<InlineResponse200>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        L.debug("End : StubMappingsApi.adminMappingsFindByMetadataPostAsync(...)");
        return call;
    }
    /**
     * Build call for adminMappingsGet
     * @param limit The maximum number of results to return (optional)
     * @param offset The start index of the results to return (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call adminMappingsGetCall(Integer limit, Integer offset, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsGetCall(...)");
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/__admin/mappings";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (limit != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("limit", limit));
        if (offset != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("offset", offset));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        L.debug("End : StubMappingsApi.adminMappingsGetCall(...)");
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call adminMappingsGetValidateBeforeCall(Integer limit, Integer offset, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsGetValidateBeforeCall(...)");
        
        com.squareup.okhttp.Call call = adminMappingsGetCall(limit, offset, progressListener, progressRequestListener);
        L.debug("End : StubMappingsApi.adminMappingsGetValidateBeforeCall(...)");
        return call;

        
        
        
        
    }

    /**
     * Get all stub mappings
     * 
     * @param limit The maximum number of results to return (optional)
     * @param offset The start index of the results to return (optional)
     * @return InlineResponse200
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public InlineResponse200 adminMappingsGet(Integer limit, Integer offset) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsGet(...)");
        ApiResponse<InlineResponse200> resp = adminMappingsGetWithHttpInfo(limit, offset);
        L.debug("End : StubMappingsApi.adminMappingsGet(...)");
        return resp.getData();
    }

    /**
     * Get all stub mappings
     * 
     * @param limit The maximum number of results to return (optional)
     * @param offset The start index of the results to return (optional)
     * @return ApiResponse&lt;InlineResponse200&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<InlineResponse200> adminMappingsGetWithHttpInfo(Integer limit, Integer offset) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsGetWithHttpInfo(...)");
        com.squareup.okhttp.Call call = adminMappingsGetValidateBeforeCall(limit, offset, null, null);
        Type localVarReturnType = new TypeToken<InlineResponse200>(){}.getType();
        L.debug("End : StubMappingsApi.adminMappingsGetWithHttpInfo(...)");
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Get all stub mappings (asynchronously)
     * 
     * @param limit The maximum number of results to return (optional)
     * @param offset The start index of the results to return (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call adminMappingsGetAsync(Integer limit, Integer offset, final ApiCallback<InlineResponse200> callback) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsGetAsync(...)");

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = adminMappingsGetValidateBeforeCall(limit, offset, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<InlineResponse200>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        L.debug("End : StubMappingsApi.adminMappingsGetAsync(...)");
        return call;
    }
    /**
     * Build call for adminMappingsPost
     * @param body  (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call adminMappingsPostCall(Body body, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsPostCall(...)");
        Object localVarPostBody = body;
        
        // create path and map variables
        String localVarPath = "/__admin/mappings";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        L.debug("End : StubMappingsApi.adminMappingsPostCall(...)");
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call adminMappingsPostValidateBeforeCall(Body body, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsPostValidateBeforeCall(...)");
        
        com.squareup.okhttp.Call call = adminMappingsPostCall(body, progressListener, progressRequestListener);
        L.debug("End : StubMappingsApi.adminMappingsPostValidateBeforeCall(...)");
        return call;

        
        
        
        
    }

    /**
     * Create a new stub mapping
     * 
     * @param body  (optional)
     * @return InlineResponse201
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public InlineResponse201 adminMappingsPost(Body body) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsPost(...)");
        ApiResponse<InlineResponse201> resp = adminMappingsPostWithHttpInfo(body);
        L.debug("End : StubMappingsApi.adminMappingsPost(...)");
        return resp.getData();
    }

    /**
     * Create a new stub mapping
     * 
     * @param body  (optional)
     * @return ApiResponse&lt;InlineResponse201&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<InlineResponse201> adminMappingsPostWithHttpInfo(Body body) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsPostWithHttpInfo(...)");
        com.squareup.okhttp.Call call = adminMappingsPostValidateBeforeCall(body, null, null);
        Type localVarReturnType = new TypeToken<InlineResponse201>(){}.getType();
        L.debug("End : StubMappingsApi.adminMappingsPostWithHttpInfo(...)");
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Create a new stub mapping (asynchronously)
     * 
     * @param body  (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call adminMappingsPostAsync(Body body, final ApiCallback<InlineResponse201> callback) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsPostAsync(...)");

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = adminMappingsPostValidateBeforeCall(body, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<InlineResponse201>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        L.debug("End : StubMappingsApi.adminMappingsPostAsync(...)");
        return call;
    }
    /**
     * Build call for adminMappingsRemoveByMetadataPost
     * @param body  (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call adminMappingsRemoveByMetadataPostCall(Body3 body, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsRemoveByMetadataPostCall(...)");
        Object localVarPostBody = body;
        
        // create path and map variables
        String localVarPath = "/__admin/mappings/remove-by-metadata";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        L.debug("End : StubMappingsApi.adminMappingsRemoveByMetadataPostCall(...)");
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call adminMappingsRemoveByMetadataPostValidateBeforeCall(Body3 body, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsRemoveByMetadataPostValidateBeforeCall(...)");
        
        com.squareup.okhttp.Call call = adminMappingsRemoveByMetadataPostCall(body, progressListener, progressRequestListener);
        L.debug("End : StubMappingsApi.adminMappingsRemoveByMetadataPostValidateBeforeCall(...)");
        return call;

        
        
        
        
    }

    /**
     * Delete stub mappings matching metadata
     * 
     * @param body  (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void adminMappingsRemoveByMetadataPost(Body3 body) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsRemoveByMetadataPost(...)");
        adminMappingsRemoveByMetadataPostWithHttpInfo(body);
        L.debug("End : StubMappingsApi.adminMappingsRemoveByMetadataPost(...)");
    }

    /**
     * Delete stub mappings matching metadata
     * 
     * @param body  (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> adminMappingsRemoveByMetadataPostWithHttpInfo(Body3 body) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsRemoveByMetadataPostWithHttpInfo(...)");
        com.squareup.okhttp.Call call = adminMappingsRemoveByMetadataPostValidateBeforeCall(body, null, null);
        L.debug("End : StubMappingsApi.adminMappingsRemoveByMetadataPostWithHttpInfo(...)");
        return apiClient.execute(call);
    }

    /**
     * Delete stub mappings matching metadata (asynchronously)
     * 
     * @param body  (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call adminMappingsRemoveByMetadataPostAsync(Body3 body, final ApiCallback<Void> callback) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsRemoveByMetadataPostAsync(...)");

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = adminMappingsRemoveByMetadataPostValidateBeforeCall(body, progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        L.debug("End : StubMappingsApi.adminMappingsRemoveByMetadataPostAsync(...)");
        return call;
    }
    /**
     * Build call for adminMappingsResetPost
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call adminMappingsResetPostCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsResetPostCall(...)");
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/__admin/mappings/reset";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        L.debug("End : StubMappingsApi.adminMappingsResetPostCall(...)");
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call adminMappingsResetPostValidateBeforeCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsResetPostValidateBeforeCall(...)");
        com.squareup.okhttp.Call call = adminMappingsResetPostCall(progressListener, progressRequestListener);
        L.debug("End : StubMappingsApi.adminMappingsResetPostValidateBeforeCall(...)");
        return call;

        
        
        
        
    }

    /**
     * Reset stub mappings
     * Restores stub mappings to the defaults defined back in the backing store
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void adminMappingsResetPost() throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsResetPost(...)");
        adminMappingsResetPostWithHttpInfo();
        L.debug("End : StubMappingsApi.adminMappingsResetPost(...)");
    }

    /**
     * Reset stub mappings
     * Restores stub mappings to the defaults defined back in the backing store
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> adminMappingsResetPostWithHttpInfo() throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsResetPostWithHttpInfo(...)");
        com.squareup.okhttp.Call call = adminMappingsResetPostValidateBeforeCall(null, null);
        L.debug("End : StubMappingsApi.adminMappingsResetPostWithHttpInfo(...)");
        return apiClient.execute(call);
    }

    /**
     * Reset stub mappings (asynchronously)
     * Restores stub mappings to the defaults defined back in the backing store
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call adminMappingsResetPostAsync(final ApiCallback<Void> callback) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsResetPostAsync(...)");
        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = adminMappingsResetPostValidateBeforeCall(progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        L.debug("End : StubMappingsApi.adminMappingsResetPostAsync(...)");
        return call;
    }
    /**
     * Build call for adminMappingsSavePost
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call adminMappingsSavePostCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsSavePostCall(...)");
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/__admin/mappings/save";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        L.debug("End : StubMappingsApi.adminMappingsSavePostCall(...)");
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call adminMappingsSavePostValidateBeforeCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsSavePostValidateBeforeCall(...)");
        com.squareup.okhttp.Call call = adminMappingsSavePostCall(progressListener, progressRequestListener);
        L.debug("End : StubMappingsApi.adminMappingsSavePostValidateBeforeCall(...)");
        return call;

        
        
        
        
    }

    /**
     * Persist stub mappings
     * Save all persistent stub mappings to the backing store
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void adminMappingsSavePost() throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsSavePost()");
        adminMappingsSavePostWithHttpInfo();
        L.debug("End : StubMappingsApi.adminMappingsSavePost()");
    }

    /**
     * Persist stub mappings
     * Save all persistent stub mappings to the backing store
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> adminMappingsSavePostWithHttpInfo() throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsSavePostWithHttpInfo()");
        com.squareup.okhttp.Call call = adminMappingsSavePostValidateBeforeCall(null, null);
        L.debug("End : StubMappingsApi.adminMappingsSavePostWithHttpInfo()");
        return apiClient.execute(call);
    }

    /**
     * Persist stub mappings (asynchronously)
     * Save all persistent stub mappings to the backing store
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call adminMappingsSavePostAsync(final ApiCallback<Void> callback) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsSavePostAsync(...)");
        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = adminMappingsSavePostValidateBeforeCall(progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        L.debug("End : StubMappingsApi.adminMappingsSavePostAsync(...)");
        return call;
    }
    /**
     * Build call for adminMappingsStubMappingIdDelete
     * @param stubMappingId The UUID of stub mapping (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call adminMappingsStubMappingIdDeleteCall(String stubMappingId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsStubMappingIdDeleteCall(...)");
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/__admin/mappings/{stubMappingId}"
            .replaceAll("\\{" + "stubMappingId" + "\\}", apiClient.escapeString(stubMappingId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        L.debug("End : StubMappingsApi.adminMappingsStubMappingIdDeleteCall(...)");
        return apiClient.buildCall(localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call adminMappingsStubMappingIdDeleteValidateBeforeCall(String stubMappingId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsStubMappingIdDeleteValidateBeforeCall(...)");
        // verify the required parameter 'stubMappingId' is set
        if (stubMappingId == null) {
            throw new ApiException("Missing the required parameter 'stubMappingId' when calling adminMappingsStubMappingIdDelete(Async)");
        }
        
        com.squareup.okhttp.Call call = adminMappingsStubMappingIdDeleteCall(stubMappingId, progressListener, progressRequestListener);
        L.debug("End : StubMappingsApi.adminMappingsStubMappingIdDeleteValidateBeforeCall(...)");
        return call;

        
        
        
        
    }

    /**
     * Delete a stub mapping
     * 
     * @param stubMappingId The UUID of stub mapping (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void adminMappingsStubMappingIdDelete(String stubMappingId) throws ApiException {
        adminMappingsStubMappingIdDeleteWithHttpInfo(stubMappingId);
    }

    /**
     * Delete a stub mapping
     * 
     * @param stubMappingId The UUID of stub mapping (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> adminMappingsStubMappingIdDeleteWithHttpInfo(String stubMappingId) throws ApiException {
        com.squareup.okhttp.Call call = adminMappingsStubMappingIdDeleteValidateBeforeCall(stubMappingId, null, null);
        return apiClient.execute(call);
    }

    /**
     * Delete a stub mapping (asynchronously)
     * 
     * @param stubMappingId The UUID of stub mapping (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call adminMappingsStubMappingIdDeleteAsync(String stubMappingId, final ApiCallback<Void> callback) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsStubMappingIdDeleteAsync(...)");
        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = adminMappingsStubMappingIdDeleteValidateBeforeCall(stubMappingId, progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        L.debug("End : StubMappingsApi.adminMappingsStubMappingIdDeleteAsync(...)");
        return call;
    }
    /**
     * Build call for adminMappingsStubMappingIdGet
     * @param stubMappingId The UUID of stub mapping (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call adminMappingsStubMappingIdGetCall(String stubMappingId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsStubMappingIdGetCall(...)");
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/__admin/mappings/{stubMappingId}"
            .replaceAll("\\{" + "stubMappingId" + "\\}", apiClient.escapeString(stubMappingId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        L.debug("End : StubMappingsApi.adminMappingsStubMappingIdGetCall(...)");
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call adminMappingsStubMappingIdGetValidateBeforeCall(String stubMappingId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsStubMappingIdGetValidateBeforeCall(...)");
        // verify the required parameter 'stubMappingId' is set
        if (stubMappingId == null) {
            throw new ApiException("Missing the required parameter 'stubMappingId' when calling adminMappingsStubMappingIdGet(Async)");
        }
        
        com.squareup.okhttp.Call call = adminMappingsStubMappingIdGetCall(stubMappingId, progressListener, progressRequestListener);
        L.debug("End : StubMappingsApi.adminMappingsStubMappingIdGetValidateBeforeCall(...)");
        return call;

        
        
        
        
    }

    /**
     * Get stub mapping by ID
     * 
     * @param stubMappingId The UUID of stub mapping (required)
     * @return InlineResponse201
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public InlineResponse201 adminMappingsStubMappingIdGet(String stubMappingId) throws ApiException {
        ApiResponse<InlineResponse201> resp = adminMappingsStubMappingIdGetWithHttpInfo(stubMappingId);
        return resp.getData();
    }

    /**
     * Get stub mapping by ID
     * 
     * @param stubMappingId The UUID of stub mapping (required)
     * @return ApiResponse&lt;InlineResponse201&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<InlineResponse201> adminMappingsStubMappingIdGetWithHttpInfo(String stubMappingId) throws ApiException {
        com.squareup.okhttp.Call call = adminMappingsStubMappingIdGetValidateBeforeCall(stubMappingId, null, null);
        Type localVarReturnType = new TypeToken<InlineResponse201>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Get stub mapping by ID (asynchronously)
     * 
     * @param stubMappingId The UUID of stub mapping (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call adminMappingsStubMappingIdGetAsync(String stubMappingId, final ApiCallback<InlineResponse201> callback) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsStubMappingIdGetAsync(...)");
        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = adminMappingsStubMappingIdGetValidateBeforeCall(stubMappingId, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<InlineResponse201>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        L.debug("End : StubMappingsApi.adminMappingsStubMappingIdGetAsync(...)");
        return call;
    }
    /**
     * Build call for adminMappingsStubMappingIdPut
     * @param stubMappingId The UUID of stub mapping (required)
     * @param body  (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call adminMappingsStubMappingIdPutCall(String stubMappingId, Body1 body, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsStubMappingIdPutCall(...)");
        Object localVarPostBody = body;
        
        // create path and map variables
        String localVarPath = "/__admin/mappings/{stubMappingId}"
            .replaceAll("\\{" + "stubMappingId" + "\\}", apiClient.escapeString(stubMappingId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        L.debug("End : StubMappingsApi.adminMappingsStubMappingIdPutCall(...)");
        return apiClient.buildCall(localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call adminMappingsStubMappingIdPutValidateBeforeCall(String stubMappingId, Body1 body, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'stubMappingId' is set
        if (stubMappingId == null) {
            throw new ApiException("Missing the required parameter 'stubMappingId' when calling adminMappingsStubMappingIdPut(Async)");
        }
        
        com.squareup.okhttp.Call call = adminMappingsStubMappingIdPutCall(stubMappingId, body, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Update a stub mapping
     * 
     * @param stubMappingId The UUID of stub mapping (required)
     * @param body  (optional)
     * @return InlineResponse201
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public InlineResponse201 adminMappingsStubMappingIdPut(String stubMappingId, Body1 body) throws ApiException {
        ApiResponse<InlineResponse201> resp = adminMappingsStubMappingIdPutWithHttpInfo(stubMappingId, body);
        return resp.getData();
    }

    /**
     * Update a stub mapping
     * 
     * @param stubMappingId The UUID of stub mapping (required)
     * @param body  (optional)
     * @return ApiResponse&lt;InlineResponse201&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<InlineResponse201> adminMappingsStubMappingIdPutWithHttpInfo(String stubMappingId, Body1 body) throws ApiException {
        com.squareup.okhttp.Call call = adminMappingsStubMappingIdPutValidateBeforeCall(stubMappingId, body, null, null);
        Type localVarReturnType = new TypeToken<InlineResponse201>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Update a stub mapping (asynchronously)
     * 
     * @param stubMappingId The UUID of stub mapping (required)
     * @param body  (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call adminMappingsStubMappingIdPutAsync(String stubMappingId, Body1 body, final ApiCallback<InlineResponse201> callback) throws ApiException {
    	L.debug("Start : StubMappingsApi.adminMappingsStubMappingIdPutAsync(...)");
        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = adminMappingsStubMappingIdPutValidateBeforeCall(stubMappingId, body, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<InlineResponse201>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        L.debug("End : StubMappingsApi.adminMappingsStubMappingIdPutAsync(...)");
        return call;
    }
}
